services:
  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
          - ./backend/.env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - servemate

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5540:5540"    
    volumes:
      - redisinsight-data:/data
    networks:
      - servemate

  litellm:
      image: ghcr.io/berriai/litellm:main-v1.78.2-nightly
      container_name: litellm
      ports:
        - "4000:4000"
      env_file:
          - ./backend/.env
      environment:
        - GROQ_API_KEY=${GROQ_API_KEY}
        - OPENROUTER_API_KEY=${OPEN_ROUTER_API_KEY}
      volumes:
        - ./litellm_config.yaml:/app/litellm_config.yaml:ro
      command: ["--host", "0.0.0.0", "--port", "4000", "--config", "/app/litellm_config.yaml"]
      restart: unless-stopped
      networks:
        - servemate

      
networks:
  servemate:

volumes:
  redis-data:
  redisinsight-data:
