services:
  redis:
    image: redis:7
    container_name: redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - servemate

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5540:5540"    
    volumes:
      - redisinsight-data:/data
    networks:
      - servemate

networks:
  servemate:

volumes:
  redis-data:
  redisinsight-data:
